### ISSUE TITLE
Cannot start cc2652p

### ISSUE THREAD

**Issue by palsbo** [codm/cc2652-raspberry-pi-module#9]
I have not been able to connect with CC2652 to zigbee2mqtt.
This is my log:
<pre><code>Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-07-13 12:03:11] info: 	z2m: Logging to console, file (filename: log.log)
[2024-07-13 12:03:11] info: 	z2m: Starting Zigbee2MQTT version 1.39.0 (commit #0326926)
[2024-07-13 12:03:11] info: 	z2m: Starting zigbee-herdsman (0.50.1)
[2024-07-13 12:03:14] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyAMA0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-07-13 12:03:14] info: 	zh:zstack:znp: Serialport opened
[2024-07-13 12:04:19] error: 	z2m: Error while starting zigbee-herdsman
[2024-07-13 12:04:19] error: 	z2m: Failed to start zigbee
[2024-07-13 12:04:19] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-07-13 12:04:19] error: 	z2m: Exiting...
[2024-07-13 12:04:20] error: 	z2m: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:341:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:86:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:129:29)
    at Zigbee.start (/app/lib/zigbee.ts:63:27)
    at Controller.start (/app/lib/controller.ts:139:27)
    at start (/app/index.js:154:5)
</code></pre>
This is my config.txt (the end of it):
<pre><code>
[all]
dtoverlay=disable-bt
enable uart=1
enable_uart=1
</code></pre>
and this is my configuration.yaml:
<pre><code>permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://127.0.0.1:1883
  pan_id: 0x3b62  # Change this to a unique value
  ext_pan_id: 0xbbdddd00dddddddd  # Change this to a unique value
  keepalive: 60
  reject_unauthorized: false
  version: 4
serial:
  port: /dev/ttyAMA0
advanced:
  baudrate: 115200
  rtscts: false
frontend:
  port: 8181

</code></pre>

**Comment by codmpm** [comment]
Hey @palsbo,

could you try to enable UART in `raspi-config`? That should do the trick without manually editing `config.tyt`.

Albeit, just saw your error message: 
```
 Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
```

This looks like it has nothing to do with the serial port....

Best,
Patrik

**Comment by palsbo** [comment]
Hi Patrik
Thanks for quick response. After a lot of testing, I managed to make it start. However it is very difficult to pair devices, compared with other adapters. I do use the external antenne.
I gues, that the time-out problem might have to do with lack of sensitivity of the receiver???.
Regards
Erik

________________________________
Fra: Patrik Mayer ***@***.***>
Sendt: 15. juli 2024 12:46
Til: codm/cc2652-raspberry-pi-module ***@***.***>
Cc: Erik Palsbo ***@***.***>; Mention ***@***.***>
Emne: Re: [codm/cc2652-raspberry-pi-module] Cannot start cc2652p (Issue #9)


Hey @palsbo<https://github.com/palsbo>,

could you try to enable UART in raspi-config? That should do the trick without manually editing config.txt.

Albeit, just saw your error message:

 Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby


This looks like it has nothing to do with the serial port....

Best,
Patrik

**Comment by codmpm** [comment]
Hmm, that seems odd.
Could you provide a picture of the module and the attached antenna?
